version: '2.2'
services:
  pin-up:
    build: ./pin-up
    container_name: pin-up
    depends_on:
      - 'mongo'
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - './pin-up:/opt/pin-up:cached'
  mongo:
    image: 'mongo:4.2.6-bionic'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db
    restart: always
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    restart: always